config/routes.rb
Rails.application.routes.draw do

  root 'tags#index' , as: 'home'

  resources :tags do
    resources :products
  end

  resources :products do
    resources :reviews
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :tag
  has_many :review

  validates_uniqueness_of :productname

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates_uniqueness_of :username
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :product
  
  validates_uniqueness_of :tagname
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @tag = Tag.find(params[:tag_id])
    @product = @tag.Product.all
  end

  def new
    @tag = Tag.find(params[:tag_id])
  end

  def create
    @tag = Tag.find(params[:tag_id])
    @product = @tag.product.create(product_params)
    redirect_to tag_path(@tag), notice: 'New Product stored successfully.'
  end

  def show
    @tag = Tag.find(params[:id])
    @product = @tag.product.find(params[:tag_id])
  end

  def edit
    @tag = Tag.find(params[:id])
    @product = @tag.product.find(params[:tag_id])
  end

  def update
    @tag = Tag.find(params[:id])
    @product = @tag.product.update(product_params)
    redirect_to tag_path(@product), notice: 'Product updated successfully.'
  end

  def destroy
    @tag = Tag.find(params[:id])
    @product = @tag.product.find(params[:tag_id])
    if(@product.destroy)
      redirect_to tag_path(@tag), notice: 'Product deleted successfully.'
    else
      redirect_to tag_product_path(@product)
    end
  end

  private def product_params
    params.require(:product).permit(:productname)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @product = Product.find_by(params[:product_id])
    @review = @product.review.create(review_params)
    redirect_to tag_path(@product)
  end

  def destroy
    @product = Product.find_by(params[:product_id])
    @review = @product.review.find(params[:id])
    @review.destroy
    redirect_to tag_path(@product)

  end

  private def review_params
      params.require(:review).permit(:username,:body)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tag = Tag.all
end

def new
  @tag = Tag.new
end

def create
  #render plain: params[:tag].inspect
  @tag = Tag.new(tag_params)
  if(@tag.save)
    redirect_to @tag, notice: 'New Category created successfully.'
  else
    render 'new'
  end
end

def show
    @tag = Tag.find(params[:id])
end

def edit
    @tag = Tag.find(params[:id])
end

def update
    @tag = Tag.find_by(params[:id])
    if(@tag.update(tag_params))
      redirect_to @tag, notice: 'Category updated successfully.'
    else
      render 'edit'
    end
end

def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to tags_path,  notice: 'Category deleted successfully.'
end

private def tag_params
  params.require(:tag).permit(:tagname)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css'%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

    <body>

      <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">
        <%= link_to "Home" ,home_path , :class => 'btn btn-lg btn-block btn-outline-primary' %>
      </h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <%= link_to "Add New Category" ,new_tag_path , :class => 'btn btn-lg btn-block btn-outline-primary' %>
      </nav>
    </div>

    <div class="container">
      <%= yield %>
    </div>
    </body>
</html>

app/views/products/_index.html.erb
<p id="notice"><%= notice %></p>
<h3 class="text-center">PRODUCT DETAILS</h3>
<%= link_to "Add Product" ,new_tag_product_path(@tag), :class => 'btn btn-outline-primary' %>
<br/>
<% @tag.product.each do |product| %>
<div class="card body">
  <h3> Product Name : <%= product.productname %></h3>
  <%= link_to "Read More" ,tag_product_path(product), :class => 'btn btn-outline-primary' %>
</div>
<br/>
<% end %>

app/views/products/edit.html.erb
<h3 class="text-center">Edit Product Detail</h3>

<%= form_for([@tag, @tag.product.build]) do |f| %>

<p>
  <%= f.label :productname %><br>
  <%= f.text_field :productname %>
</p>
<p>
  <%= f.submit("Edit Product",{:class => 'btn btn-outline-primary'}) %>
</p>
<% end %>

app/views/products/new.html.erb
<h3 class="text-center">Add New Products</h3>

<%= form_for([@tag, @tag.product.build]) do |f| %>

<p>
  <%= f.label :productname %><br>
  <%= f.text_field :productname , required: true %>
</p>
<p>
  <%= f.submit("Add Product",{:class => 'btn btn-outline-primary'}) %>
</p>
<% end %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h3>Product Name : <%= @product.productname %></h3>
<%= link_to "Edit", edit_tag_product_path(@product), :class => 'btn btn-outline-primary' %>
<%= link_to "Delete", tag_product_path(@product), method: :delete, data: {confirm: 'Are You Sure?'}, :class => 'btn btn-outline-danger' %>
</div>
<hr>

<%= render 'reviews/index' %>
<%= render 'reviews/new' %>

app/views/reviews/_index.html.erb
<h3> Comments</h3>
<% @product.review.each do |review| %>
<div class="card body">
    <p><strong><%= review.username %></strong>
      : <%= review.body %>
      <%= link_to '[X]', [review.product, review],
                          method: :delete,
                          data: { confirm: 'Are you sure?'} %>
      </p>
</div>
<% end %>

app/views/reviews/_new.html.erb
<h3> Add Comments</h3>
<%= form_for([@product, @product.review.build]) do |f| %>
<p>
  <%= f.label :username %><br>
  <%= f.text_field :username , required: true %>
</p>
<p>
  <%= f.label :body %><br>
  <%= f.text_field :body , required: true %>
</p>
<p>
  <%= f.submit({ :class => 'btn btn-outline-primary'}) %>
</p>
<% end %>

app/views/tags/edit.html.erb
<h3 class="text-center">Edit Category</h3>

<%= form_for @tag, url: tag_path do |f| %>

<p>
  <%= f.label :tagname ,"Category Name" %><br>
  <%= f.text_field :tagname , required: true %>
</p>
<p>
  <%= f.submit("Update Category",{:class => 'btn btn-outline-primary'}) %>
</p>
<% end %>

app/views/tags/index.html.erb
<h3 class="text-center">CATEGORY DETAILS</h3>
<% @tag.each do |tags| %>
<div class="card body">
  <h3> Category Name : <%= tags.tagname %></h3>
  <%= link_to "Read More" ,tag_path(tags), :class => 'btn btn-outline-primary' %>
</div>
<br>
<% end %>

app/views/tags/new.html.erb
<h3 class="text-center">Add New Category</h3>

<%= form_with model: @tag, url: tags_path do |f| %>
<% if @tag.errors.any? %>
    <% @tag.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
<p>
  <%= f.label :tagname,"Category Name" %><br>
  <%= f.text_field :tagname , required: true %>
</p>
<p>
  <%= f.submit("Add Category", {:class => 'btn btn-outline-primary'}) %>
</p>
<% end %>

app/views/tags/show.html.erb
<div class="container">
<h3>Category Name : <%= @tag.tagname %></h3>
<%= link_to "Edit", edit_tag_path(@tag), :class => 'btn btn-outline-primary' %>
<%= link_to "Delete", tag_path(@tag), method: :delete, data: {confirm: 'Are You Sure?'}, :class => 'btn btn-outline-danger' %>
</div>
<hr>
<%= render 'products/index' %>